### ISSUE TITLE
Siri think volume as light dimmer

### ISSUE THREAD

**Issue by toshibochan** [solowalker27/homebridge-onkyo#12]
Siri think volume as light dimmer, so if I as to set the light to 20% the receiver volume go to 20%.  Can this be fixed?

**Comment by solowalker27** [comment]
If you're using the optional `volume_dimmer` accessory, that's expected. There's currently no way for volume levels to exposed natively like that in HomeKit. Using a dimmable lightbulb accessory in place of proper volume support is a bit of hack but it's the best I and others have been able to come up with so far. If you have another idea, I'd be happy to hear it.
