### ISSUE TITLE
Change name for installation 

### ISSUE THREAD

**Issue by toshibochan** [solowalker27/homebridge-onkyo#2]
You can change the name for install? Because “sudo npm install -g homebridge-onkyo” not install your homebridge-onkyo. Maybe you can change to homebridge-onkyo2?

**Comment by solowalker27** [comment]
I haven't published this to npm. If you want to install this version, you'd have to either download it from GitHub to your computer, navigate into the folder and run `sudo install -g .` or install it by giving npm a location to install from using something like `sudo install -g git+https://git@github.com/solowalker27/homebridge-onkyo.git`.
