### ISSUE TITLE
one receiver and main and zone2

### ISSUE THREAD

**Issue by toshibochan** [solowalker27/homebridge-onkyo#3]
I want use one receiver and in the config.json I add Main and Zone 2. but main and zone 2 is conflicting.

**Comment by toshibochan** [comment]
this not possible to add main and zone 2 in one receiver? when use only Main or Zone 2 work good but I like to use both. in the future I like to add zone3.

**Comment by solowalker27** [comment]
I don't use or have multiple zones. Can you share more details about what the problem is? How do they conflict and how have you added them? What does your config look like and what behavior do you see?

**Comment by toshibochan** [comment]
exemplo same receiver main and zone 2in the config.json

"platforms": [{
       "platform": "Onkyo",
       "name": "Onkyo",
       "receivers": [
           {
               "model": "TX-NR609",
               "ip_address": "10.0.1.6",
               "poll_status_interval": "3000",
               "max_volume": "55",
               "map_volume_100": true,
               "name": "Receiver",
               "inputs": {
                   "dvd": "Blu-ray",
                   "video2": "Switch",
                   "video3": "Xbox",
                   "video6": "Apple TV",
                   "video4": "AUX",
                   "cd": "TV/CD"
               },
               "volume_dimmer": true,
   			"switch_service": false
     }, {
               "model": "TX-NR609",
               "ip_address": "10.0.1.6",
               "poll_status_interval": "3000",
               "max_volume": "55",
               "map_volume_100": true,
               "name": "zone 2 Receiver",
               "zone": "zone2",
               "inputs": {
                   "dvd": "Blu-ray",
                   "video2": "Switch",
                   "video3": "Xbox",
                   "video6": "Apple TV",
                   "video4": "AUX",
                   "cd": "TV/CD"
               },
               "volume_dimmer": true,
   			"switch_service": false

**Comment by toshibochan** [comment]
the problem is when main is working the zone 2 don't work but some times zone 2 work and main don't work.

**Comment by solowalker27** [comment]
Like I mentioned before, I don't really use zone 2 so I can't test this fully. But I added a second receiver to my list that used zone 2 like you have up there and it was created successfully and I was able to turn on and off both the main zone and zone 2. So it seems to be working for me now. Maybe try again with the latest changes?

**Comment by solowalker27** [comment]
Hopefully you got this figured out. If not, feel free to reopen or create a new issue.
