### ISSUE TITLE
can't install plugin

### ISSUE THREAD

**Issue by bkonijn** [solowalker27/homebridge-onkyo#4]
Hi, I cannot install the plugin (not 0.7.0 nor 0.6.5). "This is related to npm not being able to find a file." Am I doing something wrong?

**Comment by toshibochan** [comment]
install doing
sudo npm install -g https://github.com/solowalker27/homebridge-onkyo.git

**Comment by ghost** [comment]
I get the same error message even with: `sudo npm install -g https://github.com/solowalker27/homebridge-onkyo.git`

**Comment by toshibochan** [comment]
Try:
Sudo su
sudo npm install -g https://github.com/solowalker27/homebridge-onkyo.git

**Comment by ghost** [comment]
still the same problem. I also get the same error when I try to install the original git ToddGreenfield/homebridge-onkyo

**Comment by toshibochan** [comment]
Try
sudo npm install -g --unsafe-perm https://github.com/solowalker27/homebridge-onkyo.git

**Comment by toshibochan** [comment]
@andjandre you was able to install? if not try:

sudo su
sudo npm install -g --unsafe-perm https://github.com/solowalker27/homebridge-onkyo.git

**Comment by toshibochan** [comment]
@andjandre you was able to install? If was able close the issue
