### ISSUE TITLE
TV input

### ISSUE THREAD

**Issue by csupi003** [solowalker27/homebridge-onkyo#9]
Hello, 

I have a TX-NR575E and works great if I add TX-NR609 in the config. The only thing I'm missing is to select 'TV' input. I tried different models in config but had no luck. 

Is it possible to set TV input in this plugin ? 
Thanks in advance,

**Comment by solowalker27** [comment]
I don't have an easy way of overriding the inputs for the given model. You'd just have to find another model that's closer to what your model is. I know it's not as easy as it could be to look, but you can check `node_modules/eiscp/eiscp-commands.json` for the different models you can try. Searching for `"tv"` will show you all the model sets that include that input as an option. Then search for the definition of the model set and try one of the models listed there. It's just going to be a lot of trial and error to find the best one that works for your usage.
